name: Generate Snake
on:
  schedule: [{ cron: "0 0 * * *" }]  # daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: danielwellz
          outputs: |
            dist/snake.svg
            dist/snake.gif
      - uses: actions/upload-artifact@v4
        with:
          name: snake-art
          path: dist/
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push snake assets
        run: |
          mkdir -p dist
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          cp -r dist/* .
          git add snake.svg snake.gif || true
          git commit -m "chore: update snake ğŸ" || echo "No changes to commit"
          git push
